# Completion

In [1]:
import pandas as pd
from IPython.display import clear_output



Yokosuka_Sen = pd.read_excel(r"C:\Users\andyb\Coding\Tsugi wa GitHub\Project Yokosuka-Narita Fare Caculator\Yokosuka_Sobu_NaritaAirport Line.xlsx",'Yokosuka Line')
Sobu_kaisoku_Sen = pd.read_excel(r"C:\Users\andyb\Coding\Tsugi wa GitHub\Project Yokosuka-Narita Fare Caculator\Yokosuka_Sobu_NaritaAirport Line.xlsx",'Sobu Line (Rapid)')
Narita_Kuko_Sen = pd.read_excel(r"C:\Users\andyb\Coding\Tsugi wa GitHub\Project Yokosuka-Narita Fare Caculator\Yokosuka_Sobu_NaritaAirport Line.xlsx",'Narita Line (Airport)')

JR_East_Fares_Table_raw = pd.read_html('https://jr-group.jp/higashinihon-fare/',match='JR東日本幹線運賃表')
JR_East_Fares = JR_East_Fares_Table_raw[0].copy()
JR_East_Fares_ENG = JR_East_Fares.set_axis(['Distance Brackets (km)','Fare of One-Way (円)'],axis=1)
list_of_price_yen = JR_East_Fares_ENG['Fare of One-Way (円)'].tolist()
list_of_price = [s.strip('円') for s in list_of_price_yen]
JR_East_Fares_ENG['Fare of One-Way (円)'] = list_of_price


JO0119 = Yokosuka_Sen.iloc[:,[0,1,3]]
JO2028 = Sobu_kaisoku_Sen.iloc[:,[0,1,3]]
JO2937 = Narita_Kuko_Sen.iloc[:,[0,1,3]]

Go_Through = [JO0119,JO2028,JO2937]
JO0137_unfinish1 = pd.concat(Go_Through)
JO0137_unfinish2 = JO0137_unfinish1.reset_index(drop=True)
Total_Distance = []
result = 0
for i in range(len(JO0137_unfinish2)):
    result +=JO0137_unfinish2.values[i,2]
    Total_Distance.append(round(result,1))
JO0137_unfinish2['Bussiness Distance (km)'] = Total_Distance
JO0137 = JO0137_unfinish2


for i in range(len(JO0137)):
    print(f"{JO0137.values[i,0]} - {JO0137.values[i,1]}")
clear_output(wait = True)
Go = int(input('Please enter the Starting Point (using Number of Station code below)'))
Stop = int(input('Please enter the Stop Point (using Number of Station code below)'))
if Go <= 10 or Stop <= 10:
    Go_info = str('JO' + '0' + str(Go))
    Stop_info = str('JO' + '0' + str(Stop))
else:
    Go_info = str('JO' + str(Go))
    Stop_info = str('JO' + str(Stop))   
JO0137_list = JO0137['Station No.'].tolist()
if Go_info not in JO0137_list and Stop_info not in JO0137_list:
    print(f"Information incorrect, please make sure you have enter correct Station code, maximum number is: {len(JO0137_list)}")
else:
    print(f"Your trip is: \n  Departure Station: {JO0137.values[Go-1,1]} \n  Arrival Station: {JO0137.values[Stop-1,1]}")

Travelling = 0
for i in range(Go,Stop):
    Travelling += JO0137.values[i,2]
Travelling_2 = round(Travelling,1)
print(f"\nThe total travel length is {Travelling_2}")
bracket_km = JR_East_Fares_ENG.values[:,0]
ticket_price = [a.strip(',') for a in list_of_price]
for i in range(len(bracket_km)):
    bracket_pos = str(bracket_km[i]).split('-')
    if int(bracket_pos[0]) <= Travelling_2 <= int(bracket_pos[1]):
        print(f"The ticket price is: ¥{ticket_price[i]}")
        break

Your trip is:
  Departure Station: Kurihama
  Arrival Station: Narita Airport Terminal 1

The total travel length is 147.4
The ticket price is: ¥2,640

# Stage 1: Preperation

## Part 0: Import Package

In [81]:
import pandas as pd
from IPython.display import clear_output

## Part 1: Get Data

### Yokosuka Line (JO01 - JO19)

In [82]:
Yokosuka_Sen = pd.read_excel(r"C:\Delta\Yokosuka_Sobu_NaritaAirport Line.xlsx",'Yokosuka Line')
Yokosuka_Sen.head(100)

,Station No.,Station,Japanese,Distance Between Stations (km),Location,Location2
0,JO01,Kurihama,久里浜,0.0,Yokosuka,Kanagawa
1,JO02,Kinugasa,衣笠,4.6,Yokosuka,Kanagawa
2,JO03,Yokosuka,横須賀,3.4,Yokosuka,Kanagawa
3,JO04,Taura,田浦,2.1,Yokosuka,Kanagawa
4,JO05,Higashi-Zushi,東逗子,3.4,Zushi,Kanagawa
5,JO06,Zushi,逗子,2.0,Zushi,Kanagawa
6,JO07,Kamakura,鎌倉,3.9,Kamakura,Kanagawa
7,JO08,Kita-Kamakura,北鎌倉,2.2,Kamakura,Kanagawa
8,JO09,Ōfuna,大船,2.3,Kamakura,Kanagawa
9,JO10,Totsuka,戸塚,5.6,"Totsuka-ku, Yokohama",Kanagawa
10,JO11,Higashi-Totsuka,東戸塚,4.2,"Totsuka-ku, Yokohama",Kanagawa
11,JO12,Hodogaya,保土ヶ谷,4.9,"Hodogaya-ku, Yokohama",Kanagawa
12,JO13,Yokohama,横浜,3.0,"Nishi-ku, Yokohama",Kanagawa
13,JO14,Shin-Kawasaki,新川崎,7.1,"Saiwai-ku, Kawasaki",Kanagawa
14,JO15,Musashi-Kosugi,武蔵小杉,2.7,"Nakahara-ku, Kawasaki",Kanagawa
15,JO16,Nishi-Ōi,西大井,6.4,Shinagawa,Tokyo
16,JO17,Shinagawa,品川,3.6,Minato,Tokyo
17,JO18,Shimbashi,新橋,4.9,Minato,Tokyo
18,JO19,Tokyo,東京,1.9,Chiyoda,Tokyo

### Sobu Line (JO20 - JO28)

In [83]:
Sobu_kaisoku_Sen = pd.read_excel(r"C:\Delta\Yokosuka_Sobu_NaritaAirport Line.xlsx",'Sobu Line (Rapid)')
Sobu_kaisoku_Sen.head(100)

,Station No.,Station,Japanese,Distance Between Stations (km),Location,Location2
0,JO20,Shin-Nihombashi,新日本橋,1.2,Chūō,Tokyo
1,JO21,Bakurochō,馬喰町,1.1,Chūō,Tokyo
2,JO22,Kinshichō,錦糸町,2.5,Sumida,Tokyo
3,JO23,Shin-Koiwa,新小岩,5.2,Katsushika,Tokyo
4,JO24,Ichikawa,市川,5.4,Ichikawa,Chiba
5,JO25,Funabashi,船橋,7.8,Funabashi,Chiba
6,JO26,Tsudanuma,津田沼,3.5,Narashino,Chiba
7,JO27,Inage,稲毛,9.2,"Inage-ku, Chiba",Chiba
8,JO28,Chiba,千葉,3.3,"Chūō-ku, Chiba",Chiba

### Narita Line (JO29-JO37)

In [84]:
Narita_Kuko_Sen = pd.read_excel(r"C:\Delta\Yokosuka_Sobu_NaritaAirport Line.xlsx",'Narita Line (Airport)')
Narita_Kuko_Sen.head(100)

,Station No.,Station,Japanese,Distance Between Stations (km),Location,Location2
0,JO29,Higashi-Chiba,東千葉,0.9,Chūō-ku,Chiba
1,JO30,Tsuga,都賀,3.3,Wakaba-ku,Chiba
2,JO31,Yotsukaidō,四街道,3.5,Yotsukaidō,Chiba
3,JO32,Monoi,物井,4.2,Yotsukaidō,Chiba
4,JO33,Sakura,佐倉,4.2,Sakura,Chiba
5,JO34,Shisui,酒々井,6.4,Shisui,Chiba
6,JO35,Narita,成田,6.7,Narita,Chiba
7,JO36,Narita Airport Terminal 2·3,空港第２ビル,9.8,Narita,Chiba
8,JO37,Narita Airport Terminal 1,成田空港,1.0,Narita,Chiba

### JR East Fares Table

#### Original Version

In [85]:
JR_East_Fares_Table_raw = pd.read_html('https://jr-group.jp/higashinihon-fare/',match='JR東日本幹線運賃表')
JR_East_Fares = JR_East_Fares_Table_raw[0].copy()
JR_East_Fares.head(50)

   営業キロ  （運賃計算キロ）  km     片道運賃
0                 1-3     150円
1                 4-6     190円
2                7-10     200円
3               11-15     240円
4               16-20     330円
5               21-25     420円
6               26-30     510円
7               31-35     590円
8               36-40     680円
9               41-45     770円
10              46-50     860円
11              51-60     990円
12              61-70   1,170円
13              71-80   1,340円
14              81-90   1,520円
15             91-100   1,690円
16            101-120   1,980円
17            121-140   2,310円
18            141-160   2,640円
19            161-180   3,080円
20            181-200   3,410円
21            201-220   3,740円
22            221-240   4,070円
23            241-260   4,510円
24            261-280   4,840円
25            281-300   5,170円
26            301-320   5,500円
27            321-340   5,720円
28            341-360   6,050円
29            361-380   6,380円
30            381-400   6,600円
31            401-420   6,930円
32            421-440   7,150円
33            441-460   7,480円
34            461-480   7,700円
35            481-500   8,030円
36            501-520   8,360円
37            521-540   8,580円
38            541-560   8,910円
39            561-580   9,130円
40            581-600   9,460円
41            601-640   9,790円
42            641-680  10,010円
43            681-720  10,340円
44            721-760  10,670円
45            761-800  11,000円
46            801-840  11,330円
47            841-880  11,550円
48            881-920  11,880円
49            921-960  12,210円

#### Translated Version

In [86]:
JR_East_Fares_ENG = JR_East_Fares.set_axis(['Distance Brackets (km)','Fare of One-Way (円)'],axis=1)
list_of_price_yen = JR_East_Fares_ENG['Fare of One-Way (円)'].tolist()

list_of_price = [s.strip('円') for s in list_of_price_yen]
JR_East_Fares_ENG['Fare of One-Way (円)'] = list_of_price
#print(list_of_price_yen)
#print(list_of_price)

JR_East_Fares_ENG.head(50)

   Distance Brackets (km) Fare of One-Way (円)
0                     1-3                 150
1                     4-6                 190
2                    7-10                 200
3                   11-15                 240
4                   16-20                 330
5                   21-25                 420
6                   26-30                 510
7                   31-35                 590
8                   36-40                 680
9                   41-45                 770
10                  46-50                 860
11                  51-60                 990
12                  61-70               1,170
13                  71-80               1,340
14                  81-90               1,520
15                 91-100               1,690
16                101-120               1,980
17                121-140               2,310
18                141-160               2,640
19                161-180               3,080
20                181-200               3,410
21                201-220               3,740
22                221-240               4,070
23                241-260               4,510
24                261-280               4,840
25                281-300               5,170
26                301-320               5,500
27                321-340               5,720
28                341-360               6,050
29                361-380               6,380
30                381-400               6,600
31                401-420               6,930
32                421-440               7,150
33                441-460               7,480
34                461-480               7,700
35                481-500               8,030
36                501-520               8,360
37                521-540               8,580
38                541-560               8,910
39                561-580               9,130
40                581-600               9,460
41                601-640               9,790
42                641-680              10,010
43                681-720              10,340
44                721-760              10,670
45                761-800              11,000
46                801-840              11,330
47                841-880              11,550
48                881-920              11,880
49                921-960              12,210

## Part 2: Modify Data

### Yokosuka Line (JO01 - JO19)

In [87]:
JO0119 = Yokosuka_Sen.iloc[:,[0,1,3]]
JO0119.head(100)

   Station No.          Station  Distance Between Stations (km)
0         JO01         Kurihama                             0.0
1         JO02         Kinugasa                             4.6
2         JO03         Yokosuka                             3.4
3         JO04            Taura                             2.1
4         JO05    Higashi-Zushi                             3.4
5         JO06            Zushi                             2.0
6         JO07         Kamakura                             3.9
7         JO08    Kita-Kamakura                             2.2
8         JO09            Ōfuna                             2.3
9         JO10          Totsuka                             5.6
10        JO11  Higashi-Totsuka                             4.2
11        JO12         Hodogaya                             4.9
12        JO13         Yokohama                             3.0
13        JO14    Shin-Kawasaki                             7.1
14        JO15   Musashi-Kosugi                             2.7
15        JO16         Nishi-Ōi                             6.4
16        JO17        Shinagawa                             3.6
17        JO18        Shimbashi                             4.9
18        JO19            Tokyo                             1.9

### Sobu Line (JO20 - JO28)

In [88]:
JO2028 = Sobu_kaisoku_Sen.iloc[:,[0,1,3]]
JO2028.head(100)

  Station No.          Station  Distance Between Stations (km)
0        JO20  Shin-Nihombashi                             1.2
1        JO21        Bakurochō                             1.1
2        JO22        Kinshichō                             2.5
3        JO23       Shin-Koiwa                             5.2
4        JO24         Ichikawa                             5.4
5        JO25        Funabashi                             7.8
6        JO26        Tsudanuma                             3.5
7        JO27            Inage                             9.2
8        JO28            Chiba                             3.3

### Narita Line (JO29-JO37)

In [89]:
JO2937 = Narita_Kuko_Sen.iloc[:,[0,1,3]]
JO2937.head(100)

  Station No.                      Station  Distance Between Stations (km)
0        JO29                Higashi-Chiba                             0.9
1        JO30                        Tsuga                             3.3
2        JO31                   Yotsukaidō                             3.5
3        JO32                        Monoi                             4.2
4        JO33                       Sakura                             4.2
5        JO34                       Shisui                             6.4
6        JO35                       Narita                             6.7
7        JO36  Narita Airport Terminal 2·3                             9.8
8        JO37    Narita Airport Terminal 1                             1.0

### Yokosuka - Sobu (Rapid) - Narita (Airport) Line (JO01 - JO37)

#### Before adding Column: Total Distance (km)

In [90]:
Go_Through = [JO0119,JO2028,JO2937]
JO0137_unfinish1 = pd.concat(Go_Through)
JO0137_unfinish2 = JO0137_unfinish1.reset_index(drop=True)
JO0137_unfinish2.head(100)

   Station No.                      Station  Distance Between Stations (km)
0         JO01                     Kurihama                             0.0
1         JO02                     Kinugasa                             4.6
2         JO03                     Yokosuka                             3.4
3         JO04                        Taura                             2.1
4         JO05                Higashi-Zushi                             3.4
5         JO06                        Zushi                             2.0
6         JO07                     Kamakura                             3.9
7         JO08                Kita-Kamakura                             2.2
8         JO09                        Ōfuna                             2.3
9         JO10                      Totsuka                             5.6
10        JO11              Higashi-Totsuka                             4.2
11        JO12                     Hodogaya                             4.9
12        JO13                     Yokohama                             3.0
13        JO14                Shin-Kawasaki                             7.1
14        JO15               Musashi-Kosugi                             2.7
15        JO16                     Nishi-Ōi                             6.4
16        JO17                    Shinagawa                             3.6
17        JO18                    Shimbashi                             4.9
18        JO19                        Tokyo                             1.9
19        JO20              Shin-Nihombashi                             1.2
20        JO21                    Bakurochō                             1.1
21        JO22                    Kinshichō                             2.5
22        JO23                   Shin-Koiwa                             5.2
23        JO24                     Ichikawa                             5.4
24        JO25                    Funabashi                             7.8
25        JO26                    Tsudanuma                             3.5
26        JO27                        Inage                             9.2
27        JO28                        Chiba                             3.3
28        JO29                Higashi-Chiba                             0.9
29        JO30                        Tsuga                             3.3
30        JO31                   Yotsukaidō                             3.5
31        JO32                        Monoi                             4.2
32        JO33                       Sakura                             4.2
33        JO34                       Shisui                             6.4
34        JO35                       Narita                             6.7
35        JO36  Narita Airport Terminal 2·3                             9.8
36        JO37    Narita Airport Terminal 1                             1.0

#### Core line of Column: Total Distance (km)

In [91]:
Total_Distance = []
result = 0
for i in range(len(JO0137_unfinish2)):
    result +=JO0137_unfinish2.values[i,2]
    #print(round(result,1))
    Total_Distance.append(round(result,1))
print(Total_Distance)

[0.0, 4.6, 8.0, 10.1, 13.5, 15.5, 19.4, 21.6, 23.9, 29.5, 33.7, 38.6, 41.6, 48.7, 51.4, 57.8, 61.4, 66.3, 68.2, 69.4, 70.5, 73.0, 78.2, 83.6, 91.4, 94.9, 104.1, 107.4, 108.3, 111.6, 115.1, 119.3, 123.5, 129.9, 136.6, 146.4, 147.4]

#### After adding Column: Total Distance (km)

In [92]:
JO0137_unfinish2['Bussiness Distance (km)'] = Total_Distance
JO0137 = JO0137_unfinish2
JO0137.head(100)

,Station No.,Station,Distance Between Stations (km),Bussiness Distance (km)
0,JO01,Kurihama,0.0,0.0
1,JO02,Kinugasa,4.6,4.6
2,JO03,Yokosuka,3.4,8.0
3,JO04,Taura,2.1,10.1
4,JO05,Higashi-Zushi,3.4,13.5
5,JO06,Zushi,2.0,15.5
6,JO07,Kamakura,3.9,19.4
7,JO08,Kita-Kamakura,2.2,21.6
8,JO09,Ōfuna,2.3,23.9
9,JO10,Totsuka,5.6,29.5
10,JO11,Higashi-Totsuka,4.2,33.7
11,JO12,Hodogaya,4.9,38.6
12,JO13,Yokohama,3.0,41.6
13,JO14,Shin-Kawasaki,7.1,48.7
14,JO15,Musashi-Kosugi,2.7,51.4
15,JO16,Nishi-Ōi,6.4,57.8
16,JO17,Shinagawa,3.6,61.4
17,JO18,Shimbashi,4.9,66.3
18,JO19,Tokyo,1.9,68.2
19,JO20,Shin-Nihombashi,1.2,69.4
20,JO21,Bakurochō,1.1,70.5
21,JO22,Kinshichō,2.5,73.0
22,JO23,Shin-Koiwa,5.2,78.2
23,JO24,Ichikawa,5.4,83.6
24,JO25,Funabashi,7.8,91.4
25,JO26,Tsudanuma,3.5,94.9
26,JO27,Inage,9.2,104.1
27,JO28,Chiba,3.3,107.4
28,JO29,Higashi-Chiba,0.9,108.3
29,JO30,Tsuga,3.3,111.6
30,JO31,Yotsukaidō,3.5,115.1
31,JO32,Monoi,4.2,119.3
32,JO33,Sakura,4.2,123.5
33,JO34,Shisui,6.4,129.9
34,JO35,Narita,6.7,136.6
35,JO36,Narita Airport Terminal 2·3,9.8,146.4
36,JO37,Narita Airport Terminal 1,1.0,147.4

#### Adding List of Station Code

In [93]:
JO0137_list = JO0137['Station No.'].tolist()
print(JO0137_list)

['JO01', 'JO02', 'JO03', 'JO04', 'JO05', 'JO06', 'JO07', 'JO08', 'JO09', 'JO10', 'JO11', 'JO12', 'JO13', 'JO14', 'JO15', 'JO16', 'JO17', 'JO18', 'JO19', 'JO20', 'JO21', 'JO22', 'JO23', 'JO24', 'JO25', 'JO26', 'JO27', 'JO28', 'JO29', 'JO30', 'JO31', 'JO32', 'JO33', 'JO34', 'JO35', 'JO36', 'JO37']

# Stage 2: Coding

## Ask for inputs

In [94]:
for i in range(len(JO0137)):
    print(f"{JO0137.values[i,0]} - {JO0137.values[i,1]}")

clear_output(wait = True)

Go = int(input('Please enter the Starting Point (using Number of Station code below)'))
Stop = int(input('Please enter the Stop Point (using Number of Station code below)'))

if Go <= 10 or Stop <= 10:
    Go_info = str('JO' + '0' + str(Go))
    Stop_info = str('JO' + '0' + str(Stop))
else:
    Go_info = str('JO' + str(Go))
    Stop_info = str('JO' + str(Stop))

if Go_info not in JO0137_list and Stop_info not in JO0137_list:
    print(f"Information incorrect, please make sure you have enter correct Station code, maximum number is: {len(JO0137_list)}")
else:
    print(f"Your trip is: \n  Departure Station: {JO0137.values[Go-1,1]} \n  Arrival Station: {JO0137.values[Stop-1,1]}")

Your trip is:
  Departure Station: Kurihama
  Arrival Station: Narita Airport Terminal 1

## Caculation

In [97]:
Travelling = 0
for i in range(Go,Stop):
    #print(i)
    Travelling += JO0137.values[i,2]
Travelling_2 = round(Travelling,1)
print(f"The total travel length is {Travelling_2}")

The total travel length is 147.4

### Core part: match the travel km to each categories

In [101]:
bracket_km = JR_East_Fares_ENG.values[:,0]
ticket_price = [a.strip(',') for a in list_of_price]
#print(bracket_km)
for i in range(len(bracket_km)):
    bracket_pos = str(bracket_km[i]).split('-')
    if int(bracket_pos[0]) <= Travelling_2 <= int(bracket_pos[1]):
        print(f"The ticket price is: ¥{ticket_price[i]}")
        break

The price is: ¥2,640

##### Experiment: convert into Dictionary

In [ ]:
fares_dict = JR_East_Fares_ENG.set_index('Distance Brackets (km)').T.to_dict('list') 
print(fares_dict)

{'1-3': ['150'], '4-6': ['190'], '7-10': ['200'], '11-15': ['240'], '16-20': ['330'], '21-25': ['420'], '26-30': ['510'], '31-35': ['590'], '36-40': ['680'], '41-45': ['770'], '46-50': ['860'], '51-60': ['990'], '61-70': ['1,170'], '71-80': ['1,340'], '81-90': ['1,520'], '91-100': ['1,690'], '101-120': ['1,980'], '121-140': ['2,310'], '141-160': ['2,640'], '161-180': ['3,080'], '181-200': ['3,410'], '201-220': ['3,740'], '221-240': ['4,070'], '241-260': ['4,510'], '261-280': ['4,840'], '281-300': ['5,170'], '301-320': ['5,500'], '321-340': ['5,720'], '341-360': ['6,050'], '361-380': ['6,380'], '381-400': ['6,600'], '401-420': ['6,930'], '421-440': ['7,150'], '441-460': ['7,480'], '461-480': ['7,700'], '481-500': ['8,030'], '501-520': ['8,360'], '521-540': ['8,580'], '541-560': ['8,910'], '561-580': ['9,130'], '581-600': ['9,460'], '601-640': ['9,790'], '641-680': ['10,010'], '681-720': ['10,340'], '721-760': ['10,670'], '761-800': ['11,000'], '801-840': ['11,330'], '841-880': ['11,550'], '881-920': ['11,880'], '921-960': ['12,210'], '961-1,000': ['12,540'], '1,001-1,040': ['12,870'], '1,041-1,080': ['13,200'], '1,081-1,120': ['13,420'], '1,121-1,160': ['13,750'], '1,161-1,200': ['14,080'], '1,201-1,240': ['14,410'], '1,241-1,280': ['14,740'], '1,281-1,320': ['15,070'], '1,321-1,360': ['15,290'], '1,361-1,400': ['15,620'], '1,401-1,440': ['15,950'], '1,441-1,480': ['16,280'], '1,481-1,520': ['16,610'], '1,521-1,560': ['16,830'], '1,561-1,600': ['17,160'], '1,601-1,640': ['17,490'], '1,641-1,680': ['17,820'], '1,681-1,720': ['18,150'], '1,721-1,760': ['18,480'], '1,761-1,800': ['18,700'], '1,801-1,840': ['19,030'], '1,841-1,880': ['19,360'], '1,881-1,920': ['19,690'], '1,921-1,960': ['20,020'], '1,961-2,000': ['20,240'], '2,001-2,040': ['20,570'], '2,041-2,080': ['20,900'], '2,081-2,120': ['21,230'], '2,121-2,160': ['21,560'], '2,161-2,200': ['21,890'], '2,201-2,240': ['22,110'], '2,241-2,280': ['22,440'], '2,281-2,320': ['22,770'], '2,321-2,360': ['23,100'], '2,361-2,400': ['23,430'], '2,401-2,440': ['23,650'], '2,441-2,480': ['23,980'], '2,481-2,520': ['24,310'], '2,521-2,560': ['24,640'], '2,561-2,600': ['24,970'], '2,601-2,640': ['25,300'], '2,641-2,680': ['25,520'], '2,681-2,720': ['25,850'], '2,721-2,760': ['26,180'], '2,761-2,800': ['26,510'], '2,801-2,840': ['26,840'], '2,841-2,880': ['27,060'], '2,881-2,920': ['27,390'], '2,921-2,960': ['27,720'], '2,961-3,000': ['28,050'], '3,001-3,040': ['28,380'], '3,041-3,080': ['28,710'], '3,081-3,120': ['28,930'], '3,121-3,160': ['29,260'], '3,161-3,200': ['29,590'], '3,201-3,240': ['29,920'], '3,241-3,280': ['30,250'], '3,281-3,320': ['30,580'], '3,321-3,360': ['30,800'], '3,361-3,400': ['31,130']}

###### Breakdown

In [ ]:
breakdown1 = JR_East_Fares_ENG.set_index('Distance Brackets (km)') #set the column that you wish to become an index
breakdown1.head(20)

#breakdown2 = breakdown1.T #rotate the table, in order for converting to_dict() correctly, top-down scanning {index (cell at top row) : value (cell at bottom row)}
#breakdown2.head(20)

                       Fare of One-Way (円)
Distance Brackets (km)
1-3                                    150
4-6                                    190
7-10                                   200
11-15                                  240
16-20                                  330
21-25                                  420
26-30                                  510
31-35                                  590
36-40                                  680
41-45                                  770
46-50                                  860
51-60                                  990
61-70                                1,170
71-80                                1,340
81-90                                1,520
91-100                               1,690
101-120                              1,980
121-140                              2,310
141-160                              2,640
161-180                              3,080

In [ ]:
#len(bracket_keys)
fares_dict.items()

dict_items([('1-3', ['150']), ('4-6', ['190']), ('7-10', ['200']), ('11-15', ['240']), ('16-20', ['330']), ('21-25', ['420']), ('26-30', ['510']), ('31-35', ['590']), ('36-40', ['680']), ('41-45', ['770']), ('46-50', ['860']), ('51-60', ['990']), ('61-70', ['1,170']), ('71-80', ['1,340']), ('81-90', ['1,520']), ('91-100', ['1,690']), ('101-120', ['1,980']), ('121-140', ['2,310']), ('141-160', ['2,640']), ('161-180', ['3,080']), ('181-200', ['3,410']), ('201-220', ['3,740']), ('221-240', ['4,070']), ('241-260', ['4,510']), ('261-280', ['4,840']), ('281-300', ['5,170']), ('301-320', ['5,500']), ('321-340', ['5,720']), ('341-360', ['6,050']), ('361-380', ['6,380']), ('381-400', ['6,600']), ('401-420', ['6,930']), ('421-440', ['7,150']), ('441-460', ['7,480']), ('461-480', ['7,700']), ('481-500', ['8,030']), ('501-520', ['8,360']), ('521-540', ['8,580']), ('541-560', ['8,910']), ('561-580', ['9,130']), ('581-600', ['9,460']), ('601-640', ['9,790']), ('641-680', ['10,010']), ('681-720', ['10,340']), ('721-760', ['10,670']), ('761-800', ['11,000']), ('801-840', ['11,330']), ('841-880', ['11,550']), ('881-920', ['11,880']), ('921-960', ['12,210']), ('961-1,000', ['12,540']), ('1,001-1,040', ['12,870']), ('1,041-1,080', ['13,200']), ('1,081-1,120', ['13,420']), ('1,121-1,160', ['13,750']), ('1,161-1,200', ['14,080']), ('1,201-1,240', ['14,410']), ('1,241-1,280', ['14,740']), ('1,281-1,320', ['15,070']), ('1,321-1,360', ['15,290']), ('1,361-1,400', ['15,620']), ('1,401-1,440', ['15,950']), ('1,441-1,480', ['16,280']), ('1,481-1,520', ['16,610']), ('1,521-1,560', ['16,830']), ('1,561-1,600', ['17,160']), ('1,601-1,640', ['17,490']), ('1,641-1,680', ['17,820']), ('1,681-1,720', ['18,150']), ('1,721-1,760', ['18,480']), ('1,761-1,800', ['18,700']), ('1,801-1,840', ['19,030']), ('1,841-1,880', ['19,360']), ('1,881-1,920', ['19,690']), ('1,921-1,960', ['20,020']), ('1,961-2,000', ['20,240']), ('2,001-2,040', ['20,570']), ('2,041-2,080', ['20,900']), ('2,081-2,120', ['21,230']), ('2,121-2,160', ['21,560']), ('2,161-2,200', ['21,890']), ('2,201-2,240', ['22,110']), ('2,241-2,280', ['22,440']), ('2,281-2,320', ['22,770']), ('2,321-2,360', ['23,100']), ('2,361-2,400', ['23,430']), ('2,401-2,440', ['23,650']), ('2,441-2,480', ['23,980']), ('2,481-2,520', ['24,310']), ('2,521-2,560', ['24,640']), ('2,561-2,600', ['24,970']), ('2,601-2,640', ['25,300']), ('2,641-2,680', ['25,520']), ('2,681-2,720', ['25,850']), ('2,721-2,760', ['26,180']), ('2,761-2,800', ['26,510']), ('2,801-2,840', ['26,840']), ('2,841-2,880', ['27,060']), ('2,881-2,920', ['27,390']), ('2,921-2,960', ['27,720']), ('2,961-3,000', ['28,050']), ('3,001-3,040', ['28,380']), ('3,041-3,080', ['28,710']), ('3,081-3,120', ['28,930']), ('3,121-3,160', ['29,260']), ('3,161-3,200', ['29,590']), ('3,201-3,240', ['29,920']), ('3,241-3,280', ['30,250']), ('3,281-3,320', ['30,580']), ('3,321-3,360', ['30,800']), ('3,361-3,400', ['31,130'])])